name: Build/release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_on_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Sign build files
        uses: GabrielAcostaEngler/signtool-code-sign@main
        with:
          certificate: '${{ secrets.CERTIFICATE }}'
          cert-password: '${{ secrets.PASSWORD }}'
          cert-sha1: '${{ secrets.CERTHASH }}'
          cert-description: 'Storekeeper Windows POS'
          folder: './'
          recursive: false
          timestamp-server: 'http://timestamp.digicert.com' #might be given by the Certificate provider

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-artifacts
          path: ./*.exe

  build_on_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux-artifacts
          path: ./*.txt

  pre_release:
    needs: [build_on_windows, build_on_linux]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3

      - name: Release latest main
        uses: marvinpinto/action-automatic-releases@v1.2.0
        if: github.ref == 'refs/heads/main'
        with:
          prerelease: true
          automatic_release_tag: 'main'
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            ./windows-artifacts/*.exe
            ./linux-artifacts/*.txt

      - name: Release version
        uses: marvinpinto/action-automatic-releases@v1.2.0
        if: ${{ startsWith( github.ref, 'refs/tags/' ) }}
        with:
          prerelease: true
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            ./windows-artifacts/*.exe
            ./linux-artifacts/*.txt
