name: Build/release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  pre_release:
    runs-on: ubuntu-latest
    steps:
      - name: Release version
        uses: marvinpinto/action-automatic-releases@v1.2.0
        if: ${{ startsWith( github.ref, 'refs/tags/' ) }}
        with:
          prerelease: true
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
